language: java

# To test agains multiple JDKs
jdk:
  - oraclejdk9
#  - openjdk8

#before_install:
# - sudo apt-get update -qq
# - sudo apt-get install couchdb

services:
  - couchdb

env:
  global:
   # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
   #   via the "travis encrypt" command using the project repo's public key
   - secure: "k/yRXYsKfSbSqwXSqijtSLIq/pS/D+pU7gG/w0tHRKPQAVFMqwpwStIY/rcJS5afbQKEVZahZcXR4zQmFtaw6MUAZ+fcqj8jgDfH7sHCSZEVZxks1V2P5nSgjGI6hXx7QCLjwae+f6deN33X726vOkKfV29lkcFJFA3TQ3JTJ40="

addons:
  coverity_scan:
    project:
      name: "cli/sonews"
      description: "sonews NNTP Usenet Server"
    notification_email: christian@lins.me
    build_command_prepend: mvn clean
    build_command: mvn compile package
    branch_pattern: coverity
