#!/bin/bash

CLASSPATH=/usr/share/java/sonews.jar:\
/usr/share/java/sonews-helpers.jar:\
/usr/share/java/mysql-connector-java.jar:\
/usr/share/java/glassfish-mail.jar:\
/usr/share/java/postgresql.jar

LOGFILE=/var/log/sonews.log
PIDFILE=/var/run/sonews.pid
ARGS="-mlgw -c /etc/sonews/sonews.conf -feed"
RUNAS=sonews
MAINCLASS=org.sonews.Main
JAVA=sudo -u $RUNAS /usr/bin/java

case "$1" in
  start)
    echo "Starting sonews Newsserver..."
    $JAVA -classpath $CLASSPATH $MAINCLASS $ARGS &> $LOGFILE &
    PID=$!
    echo $PID > $PIDFILE
    ;;
  stop)
    echo "Stopping sonews Newsserver..."
    PID=`cat $PIDFILE`
    STOPRES=0
    while [ $STOPRES -le 0 ]
    do
      kill -15 $PID &> /dev/null
      STOPRES=$?
      sleep 1
    done
    echo "done."
    ;;
  restart)
    $0 stop && $0 start
    ;;
  setup)
    $JAVA -classpath $CLASSPATH org.sonews.util.DatabaseSetup
    ;;
  purge)
    $JAVA -classpath $CLASSPATH org.sonews.util.Purger
    ;;
  version)
    $JAVA -classpath $CLASSPATH $MAINCLASS -version
    ;;
  *)
    echo "Usage: sonews [start|stop|restart|setup|purge]"
esac
